[2025-06-02T15:30:33.399+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_spark_connection.test_spark_task manual__2025-06-02T15:30:30.652039+00:00 [queued]>
[2025-06-02T15:30:33.429+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_spark_connection.test_spark_task manual__2025-06-02T15:30:30.652039+00:00 [queued]>
[2025-06-02T15:30:33.430+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-02T15:30:33.531+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): test_spark_task> on 2025-06-02 15:30:30.652039+00:00
[2025-06-02T15:30:33.594+0000] {standard_task_runner.py:60} INFO - Started process 256 to run task
[2025-06-02T15:30:33.611+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_spark_connection', 'test_spark_task', 'manual__2025-06-02T15:30:30.652039+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmpkvwaqcdn']
[2025-06-02T15:30:33.638+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask test_spark_task
[2025-06-02T15:30:33.764+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-02T15:30:34.213+0000] {task_command.py:423} INFO - Running <TaskInstance: test_spark_connection.test_spark_task manual__2025-06-02T15:30:30.652039+00:00 [running]> on host 7824fb585b1c
[2025-06-02T15:30:34.537+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_spark_connection' AIRFLOW_CTX_TASK_ID='test_spark_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T15:30:30.652039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T15:30:30.652039+00:00'
[2025-06-02T15:30:34.557+0000] {spark_submit.py:304} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-06-02T15:30:34.559+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --verbose /opt/***/dags/scripts/test_spark_job.py
[2025-06-02T15:30:34.909+0000] {spark_submit.py:649} INFO - JAVA_HOME is not set
[2025-06-02T15:30:34.932+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose /opt/***/dags/scripts/test_spark_job.py. Error code is: 1.
[2025-06-02T15:30:34.940+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_spark_connection, task_id=test_spark_task, execution_date=20250602T153030, start_date=20250602T153033, end_date=20250602T153034
[2025-06-02T15:30:34.987+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 80 for task test_spark_task (Cannot execute: spark-submit --master yarn --name arrow-spark --verbose /opt/***/dags/scripts/test_spark_job.py. Error code is: 1.; 256)
[2025-06-02T15:30:35.008+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-02T15:30:35.086+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
